env:
  global:
    - JWT_SECRET=secret
    - BCRYPT_SALT=secret
    - DATABASE_DIALECT=sqlite
    - DATABASE_URI="sqlite://./database.sqlite"
    - DATABASE_TEST_DIALECT=sqlite
    - DATABASE_TEST_URI="sqlite://./database-test.sqlite"
cache:
  yarn: true
language: node_js
node_js:
  - 10.16.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn install
  - NODE_ENV=test yarn test
  - NODE_ENV=test yarn coverage
  - yarn docs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://grinry:$GITHUB_TOKEN@github.com/grinry/event-manager-gh-pages gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
